### ISSUE TITLE
see tag gets not closed

### ISSUE THREAD

**Issue by theDashGreesun** [EWSoftware/ExtendedDocCommentsProvider#3]
Hi,
after installing the extension, the following behaviour occures.

Steps to reproduce:
- Type within an xml doc area: `<see`
- select intellisens suggestion 

Result:
`<see cref="" `
will be commited to the code.

Expected:
`<see cref=""/>` should be inserted.

The expected behavior is active after uninstalling the extension.

Information:
VS 2022 Comunity V17.4.4

**Comment by EWSoftware** [comment]
The self-closing option was left off of the `see` and `seealso` elements.  A new release will be available shortly.
